<?php
/**
 * This file is part of Vima PHP.
 *
 * (c) Vima PHP <https://github.com/lipex-org/vima-core>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

declare(strict_types=1);

namespace Vima\Core\Support\Mapping;

use Vima\Core\Config\DTOs\Setup;
use Vima\Core\Events\Contracts\EventDispatcherInterface;
use Vima\Core\Events\Dispatchers\DefaultEventDispatcher;

/**
 * Class MapGenerator
 * 
 * Generates PHP mapper classes from Setup configuration using MappingService.
 */
class MapGenerator
{
    public function __construct(
        private MappingService $mappingService,
        private ?EventDispatcherInterface $dispatcher = null
    ) {
        $this->dispatcher ??= new DefaultEventDispatcher();
    }

    public function generateRoles(Setup $setup, string $namespace): string
    {
        $roleNames = array_map(fn($role) => $role->namespace ? $role->namespace . ':' . $role->name : $role->name, $setup->roles);
        $this->mappingService->sync($roleNames, 'roles');
        $this->mappingService->save();

        $map = $this->mappingService->all('roles');
        return $this->renderClass('Roles', $namespace, $map);
    }

    public function generatePermissions(Setup $setup, string $namespace): string
    {
        $permissionNames = array_map(fn($perm) => $perm->namespace ? $perm->namespace . ':' . $perm->name : $perm->name, $setup->permissions);

        foreach ($setup->roles as $role) {
            foreach ($role->permissions as $perm) {
                if (is_string($perm)) {
                    $name = $perm;
                } else {
                    $name = $perm->namespace ? $perm->namespace . ':' . $perm->name : $perm->name;
                }
                if (!in_array($name, $permissionNames) && !str_contains(is_string($perm) ? $perm : $perm->name, '*')) {
                    $permissionNames[] = $name;
                }
            }
        }

        $this->mappingService->sync($permissionNames, 'permissions');
        $this->mappingService->save();

        $map = $this->mappingService->all('permissions');
        return $this->renderClass('Permissions', $namespace, $map);
    }

    public function generateNamespaces(string $namespace): string
    {
        $map = $this->mappingService->all('namespaces');
        return $this->renderClass('Namespaces', $namespace, $map);
    }

    private function renderClass(string $className, string $namespace, array $items): string
    {
        $php = "<?php\n";
        $php .= "/**\n";
        $php .= " * Generated by Vima Mapper. Do not edit manually.\n";
        $php .= " */\n\n";
        $php .= "declare(strict_types=1);\n\n";
        $php .= "namespace " . ltrim($namespace, '\\') . ";\n\n";
        $php .= "use Vima\Core\Support\Mapping\Mappers\EnumMapper;\n\n";
        $php .= "final class {$className} extends EnumMapper\n";
        $php .= "{\n";

        ksort($items);

        foreach ($items as $slug => $name) {
            $php .= "    public const string {$slug} = '{$name}';\n";
        }

        $php .= "}\n";

        return $php;
    }
}
